CONSTANT_PROCESS_STATUS_INIT = 1
CONSTANT_PROCESS_STATUS_LOADED = 2
CONSTANT_PROCESS_STATUS_PROCESSING = 3
CONSTANT_PROCESS_STATUS_SUCCESS = 4
CONSTANT_PROCESS_STATUS_CACHE = 5
CONSTANT_PROCESS_STATUS_FAIL = 9